# This file is used for basic analysis of a .log file generated by 
# HOOMD-blue simulations in the PRoPS Group. The code was written by 
# Mohammad (Nabi) Nabizadeh and compiled as part of the PRoPS-colloids_setup 
# Github repository by Rob Campbell.
# See more at: https://github.com/rob10campbell/PRoPS-colloids_setup

# LOAD DATA ################################################

# Load your .log file as a data frame
P.df = read.table(
  file = "~/repositories/HOOMDblue-training/sims/water/Pressure_xy.log", 
  header = T)

# CHECK DATA ###############################################

# Check the first few lines of the file to see how it is formatted
head(P.df)
# Check the data summary (min, max, mean, median, etc) for unexpected errors
summary(P.df)
# View an Excel-style table of the data
View(P.df)

# PLOT DATA ##################################################

# Plot time vs. temperature (how does temp evolve in the simulation over time)
plot(x = P.df$, y = P.df$temperature, xlab = "Time", ylab = "Temperature")

# We expect temperature to stabilize around the value we assigned kT (kT=0.1).
# Add a line at 0.1 to the plot to see if this is true
lines(x = c(-100, 2000), y = c(0.1, 0.1), lty=2, col='red', lwd=2)

# Plot time vs. pressure
plot(x = P.df$timestep, y = P.df$pressure, xlab = "Time", ylab = "Pressure")
lines(x = c(-100, 2000), y = c(0, 0), lty=2, col='red', lwd=2)

# TRACK DATA AS IT IS GENERATED ###############################

# Check the number of rows in a data frame
nrow(P.df)

# You can also replot the data as it is generated
